/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ShortUrlRouteImport } from './routes/short-url'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewArticleRouteImport } from './routes/new-article'
import { Route as NewAnnouncementRouteImport } from './routes/new-announcement'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CodeRouteImport } from './routes/$code'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicAllRouteImport } from './routes/topic.all'
import { Route as FCodeRouteImport } from './routes/f.$code'
import { Route as ArticleIdRouteImport } from './routes/article.$id'
import { Route as AuthenticatedMessageRouteImport } from './routes/_authenticated/message'
import { Route as ArticleIdEditRouteImport } from './routes/article.$id.edit'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPushLatestRouteImport } from './routes/api/public/push/latest'
import { Route as ApiPublicHooksNotifyNewArticleRouteImport } from './routes/api/public/hooks/notify-new-article'

const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortUrlRoute = ShortUrlRouteImport.update({
  id: '/short-url',
  path: '/short-url',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArticleRoute = NewArticleRouteImport.update({
  id: '/new-article',
  path: '/new-article',
  getParentRoute: () => rootRouteImport,
} as any)
const NewAnnouncementRoute = NewAnnouncementRouteImport.update({
  id: '/new-announcement',
  path: '/new-announcement',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicAllRoute = TopicAllRouteImport.update({
  id: '/topic/all',
  path: '/topic/all',
  getParentRoute: () => rootRouteImport,
} as any)
const FCodeRoute = FCodeRouteImport.update({
  id: '/f/$code',
  path: '/f/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMessageRoute = AuthenticatedMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArticleIdEditRoute = ArticleIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ArticleIdRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushLatestRoute = ApiPublicPushLatestRouteImport.update({
  id: '/api/public/push/latest',
  path: '/api/public/push/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNotifyNewArticleRoute =
  ApiPublicHooksNotifyNewArticleRouteImport.update({
    id: '/api/public/hooks/notify-new-article',
    path: '/api/public/hooks/notify-new-article',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/donate': typeof DonateRoute
  '/new-announcement': typeof NewAnnouncementRoute
  '/new-article': typeof NewArticleRoute
  '/privacy': typeof PrivacyRoute
  '/short-url': typeof ShortUrlRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/thanks': typeof ThanksRoute
  '/message': typeof AuthenticatedMessageRoute
  '/article/$id': typeof ArticleIdRouteWithChildren
  '/f/$code': typeof FCodeRoute
  '/topic/all': typeof TopicAllRoute
  '/article/$id/edit': typeof ArticleIdEditRoute
  '/api/public/hooks/notify-new-article': typeof ApiPublicHooksNotifyNewArticleRoute
  '/api/public/push/latest': typeof ApiPublicPushLatestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/donate': typeof DonateRoute
  '/new-announcement': typeof NewAnnouncementRoute
  '/new-article': typeof NewArticleRoute
  '/privacy': typeof PrivacyRoute
  '/short-url': typeof ShortUrlRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/thanks': typeof ThanksRoute
  '/message': typeof AuthenticatedMessageRoute
  '/article/$id': typeof ArticleIdRouteWithChildren
  '/f/$code': typeof FCodeRoute
  '/topic/all': typeof TopicAllRoute
  '/article/$id/edit': typeof ArticleIdEditRoute
  '/api/public/hooks/notify-new-article': typeof ApiPublicHooksNotifyNewArticleRoute
  '/api/public/push/latest': typeof ApiPublicPushLatestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$code': typeof CodeRoute
  '/donate': typeof DonateRoute
  '/new-announcement': typeof NewAnnouncementRoute
  '/new-article': typeof NewArticleRoute
  '/privacy': typeof PrivacyRoute
  '/short-url': typeof ShortUrlRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/thanks': typeof ThanksRoute
  '/_authenticated/message': typeof AuthenticatedMessageRoute
  '/article/$id': typeof ArticleIdRouteWithChildren
  '/f/$code': typeof FCodeRoute
  '/topic/all': typeof TopicAllRoute
  '/article/$id/edit': typeof ArticleIdEditRoute
  '/api/public/hooks/notify-new-article': typeof ApiPublicHooksNotifyNewArticleRoute
  '/api/public/push/latest': typeof ApiPublicPushLatestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$code'
    | '/donate'
    | '/new-announcement'
    | '/new-article'
    | '/privacy'
    | '/short-url'
    | '/sign-up'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/thanks'
    | '/message'
    | '/article/$id'
    | '/f/$code'
    | '/topic/all'
    | '/article/$id/edit'
    | '/api/public/hooks/notify-new-article'
    | '/api/public/push/latest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$code'
    | '/donate'
    | '/new-announcement'
    | '/new-article'
    | '/privacy'
    | '/short-url'
    | '/sign-up'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/thanks'
    | '/message'
    | '/article/$id'
    | '/f/$code'
    | '/topic/all'
    | '/article/$id/edit'
    | '/api/public/hooks/notify-new-article'
    | '/api/public/push/latest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$code'
    | '/donate'
    | '/new-announcement'
    | '/new-article'
    | '/privacy'
    | '/short-url'
    | '/sign-up'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/thanks'
    | '/_authenticated/message'
    | '/article/$id'
    | '/f/$code'
    | '/topic/all'
    | '/article/$id/edit'
    | '/api/public/hooks/notify-new-article'
    | '/api/public/push/latest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CodeRoute: typeof CodeRoute
  DonateRoute: typeof DonateRoute
  NewAnnouncementRoute: typeof NewAnnouncementRoute
  NewArticleRoute: typeof NewArticleRoute
  PrivacyRoute: typeof PrivacyRoute
  ShortUrlRoute: typeof ShortUrlRoute
  SignUpRoute: typeof SignUpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ThanksRoute: typeof ThanksRoute
  ArticleIdRoute: typeof ArticleIdRouteWithChildren
  FCodeRoute: typeof FCodeRoute
  TopicAllRoute: typeof TopicAllRoute
  ApiPublicHooksNotifyNewArticleRoute: typeof ApiPublicHooksNotifyNewArticleRoute
  ApiPublicPushLatestRoute: typeof ApiPublicPushLatestRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/short-url': {
      id: '/short-url'
      path: '/short-url'
      fullPath: '/short-url'
      preLoaderRoute: typeof ShortUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-article': {
      id: '/new-article'
      path: '/new-article'
      fullPath: '/new-article'
      preLoaderRoute: typeof NewArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-announcement': {
      id: '/new-announcement'
      path: '/new-announcement'
      fullPath: '/new-announcement'
      preLoaderRoute: typeof NewAnnouncementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$code': {
      id: '/$code'
      path: '/$code'
      fullPath: '/$code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/all': {
      id: '/topic/all'
      path: '/topic/all'
      fullPath: '/topic/all'
      preLoaderRoute: typeof TopicAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$code': {
      id: '/f/$code'
      path: '/f/$code'
      fullPath: '/f/$code'
      preLoaderRoute: typeof FCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/message': {
      id: '/_authenticated/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof AuthenticatedMessageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/article/$id/edit': {
      id: '/article/$id/edit'
      path: '/edit'
      fullPath: '/article/$id/edit'
      preLoaderRoute: typeof ArticleIdEditRouteImport
      parentRoute: typeof ArticleIdRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/latest': {
      id: '/api/public/push/latest'
      path: '/api/public/push/latest'
      fullPath: '/api/public/push/latest'
      preLoaderRoute: typeof ApiPublicPushLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notify-new-article': {
      id: '/api/public/hooks/notify-new-article'
      path: '/api/public/hooks/notify-new-article'
      fullPath: '/api/public/hooks/notify-new-article'
      preLoaderRoute: typeof ApiPublicHooksNotifyNewArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMessageRoute: typeof AuthenticatedMessageRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMessageRoute: AuthenticatedMessageRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ArticleIdRouteChildren {
  ArticleIdEditRoute: typeof ArticleIdEditRoute
}

const ArticleIdRouteChildren: ArticleIdRouteChildren = {
  ArticleIdEditRoute: ArticleIdEditRoute,
}

const ArticleIdRouteWithChildren = ArticleIdRoute._addFileChildren(
  ArticleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CodeRoute: CodeRoute,
  DonateRoute: DonateRoute,
  NewAnnouncementRoute: NewAnnouncementRoute,
  NewArticleRoute: NewArticleRoute,
  PrivacyRoute: PrivacyRoute,
  ShortUrlRoute: ShortUrlRoute,
  SignUpRoute: SignUpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ThanksRoute: ThanksRoute,
  ArticleIdRoute: ArticleIdRouteWithChildren,
  FCodeRoute: FCodeRoute,
  TopicAllRoute: TopicAllRoute,
  ApiPublicHooksNotifyNewArticleRoute: ApiPublicHooksNotifyNewArticleRoute,
  ApiPublicPushLatestRoute: ApiPublicPushLatestRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
