/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ShortUrlRouteImport } from './routes/short-url'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PoostRouteImport } from './routes/poost'
import { Route as NewPoostRouteImport } from './routes/new-poost'
import { Route as NewArticleRouteImport } from './routes/new-article'
import { Route as NewAnnouncementRouteImport } from './routes/new-announcement'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IllurlNocaptcha15155RouteImport } from './routes/illurl-nocaptcha-15155'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CodeRouteImport } from './routes/$code'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicAllRouteImport } from './routes/topic.all'
import { Route as Oauth2SplatRouteImport } from './routes/oauth2.$'
import { Route as FCodeRouteImport } from './routes/f.$code'
import { Route as ArticleIdRouteImport } from './routes/article.$id'
import { Route as AuthenticatedMessageRouteImport } from './routes/_authenticated/message'
import { Route as AuthenticatedIllurlApiRouteImport } from './routes/_authenticated/illurl-api'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ArticleIdEditRouteImport } from './routes/article.$id.edit'
import { Route as AuthenticatedWebhooksShareRouteImport } from './routes/_authenticated/webhooks.share'
import { Route as AuthenticatedRednoteManageRouteImport } from './routes/_authenticated/rednote.manage'
import { Route as AuthenticatedMyIllurlRouteImport } from './routes/_authenticated/my.illurl'
import { Route as AuthenticatedAdminWebhooksRouteImport } from './routes/_authenticated/admin.webhooks'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as RednoteCnFilmOpenRouteImport } from './routes/rednote.cn.$film.$open'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPushLatestRouteImport } from './routes/api/public/push/latest'
import { Route as ApiPublicOauth2TokenRouteImport } from './routes/api/public/oauth2/token'
import { Route as ApiPublicIllurlShortenRouteImport } from './routes/api/public/illurl/shorten'
import { Route as ApiPublicHooksNotifyNewArticleRouteImport } from './routes/api/public/hooks/notify-new-article'
import { Route as ApiPublicHooksIllurlExpiryRemindersRouteImport } from './routes/api/public/hooks/illurl-expiry-reminders'
import { Route as AuthenticatedAdminWebhooksIdRouteImport } from './routes/_authenticated/admin.webhooks.$id'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortUrlRoute = ShortUrlRouteImport.update({
  id: '/short-url',
  path: '/short-url',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoostRoute = PoostRouteImport.update({
  id: '/poost',
  path: '/poost',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPoostRoute = NewPoostRouteImport.update({
  id: '/new-poost',
  path: '/new-poost',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArticleRoute = NewArticleRouteImport.update({
  id: '/new-article',
  path: '/new-article',
  getParentRoute: () => rootRouteImport,
} as any)
const NewAnnouncementRoute = NewAnnouncementRouteImport.update({
  id: '/new-announcement',
  path: '/new-announcement',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IllurlNocaptcha15155Route = IllurlNocaptcha15155RouteImport.update({
  id: '/illurl-nocaptcha-15155',
  path: '/illurl-nocaptcha-15155',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicAllRoute = TopicAllRouteImport.update({
  id: '/topic/all',
  path: '/topic/all',
  getParentRoute: () => rootRouteImport,
} as any)
const Oauth2SplatRoute = Oauth2SplatRouteImport.update({
  id: '/oauth2/$',
  path: '/oauth2/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FCodeRoute = FCodeRouteImport.update({
  id: '/f/$code',
  path: '/f/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMessageRoute = AuthenticatedMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIllurlApiRoute = AuthenticatedIllurlApiRouteImport.update({
  id: '/illurl-api',
  path: '/illurl-api',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArticleIdEditRoute = ArticleIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ArticleIdRoute,
} as any)
const AuthenticatedWebhooksShareRoute =
  AuthenticatedWebhooksShareRouteImport.update({
    id: '/webhooks/share',
    path: '/webhooks/share',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRednoteManageRoute =
  AuthenticatedRednoteManageRouteImport.update({
    id: '/rednote/manage',
    path: '/rednote/manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyIllurlRoute = AuthenticatedMyIllurlRouteImport.update({
  id: '/my/illurl',
  path: '/my/illurl',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminWebhooksRoute =
  AuthenticatedAdminWebhooksRouteImport.update({
    id: '/admin/webhooks',
    path: '/admin/webhooks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const RednoteCnFilmOpenRoute = RednoteCnFilmOpenRouteImport.update({
  id: '/rednote/cn/$film/$open',
  path: '/rednote/cn/$film/$open',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushLatestRoute = ApiPublicPushLatestRouteImport.update({
  id: '/api/public/push/latest',
  path: '/api/public/push/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauth2TokenRoute = ApiPublicOauth2TokenRouteImport.update({
  id: '/api/public/oauth2/token',
  path: '/api/public/oauth2/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIllurlShortenRoute = ApiPublicIllurlShortenRouteImport.update({
  id: '/api/public/illurl/shorten',
  path: '/api/public/illurl/shorten',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNotifyNewArticleRoute =
  ApiPublicHooksNotifyNewArticleRouteImport.update({
    id: '/api/public/hooks/notify-new-article',
    path: '/api/public/hooks/notify-new-article',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIllurlExpiryRemindersRoute =
  ApiPublicHooksIllurlExpiryRemindersRouteImport.update({
    id: '/api/public/hooks/illurl-expiry-reminders',
    path: '/api/public/hooks/illurl-expiry-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminWebhooksIdRoute =
  AuthenticatedAdminWebhooksIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminWebhooksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/donate': typeof DonateRoute
  '/feedback': typeof FeedbackRoute
  '/illurl-nocaptcha-15155': typeof IllurlNocaptcha15155Route
  '/mcp': typeof McpRoute
  '/new-announcement': typeof NewAnnouncementRoute
  '/new-article': typeof NewArticleRoute
  '/new-poost': typeof NewPoostRoute
  '/poost': typeof PoostRoute
  '/privacy': typeof PrivacyRoute
  '/short-url': typeof ShortUrlRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/thanks': typeof ThanksRoute
  '/webhooks': typeof WebhooksRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/illurl-api': typeof AuthenticatedIllurlApiRoute
  '/message': typeof AuthenticatedMessageRoute
  '/article/$id': typeof ArticleIdRouteWithChildren
  '/f/$code': typeof FCodeRoute
  '/oauth2/$': typeof Oauth2SplatRoute
  '/topic/all': typeof TopicAllRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRouteWithChildren
  '/my/illurl': typeof AuthenticatedMyIllurlRoute
  '/rednote/manage': typeof AuthenticatedRednoteManageRoute
  '/webhooks/share': typeof AuthenticatedWebhooksShareRoute
  '/article/$id/edit': typeof ArticleIdEditRoute
  '/admin/webhooks/$id': typeof AuthenticatedAdminWebhooksIdRoute
  '/api/public/hooks/illurl-expiry-reminders': typeof ApiPublicHooksIllurlExpiryRemindersRoute
  '/api/public/hooks/notify-new-article': typeof ApiPublicHooksNotifyNewArticleRoute
  '/api/public/illurl/shorten': typeof ApiPublicIllurlShortenRoute
  '/api/public/oauth2/token': typeof ApiPublicOauth2TokenRoute
  '/api/public/push/latest': typeof ApiPublicPushLatestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/rednote/cn/$film/$open': typeof RednoteCnFilmOpenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$code': typeof CodeRoute
  '/donate': typeof DonateRoute
  '/feedback': typeof FeedbackRoute
  '/illurl-nocaptcha-15155': typeof IllurlNocaptcha15155Route
  '/mcp': typeof McpRoute
  '/new-announcement': typeof NewAnnouncementRoute
  '/new-article': typeof NewArticleRoute
  '/new-poost': typeof NewPoostRoute
  '/poost': typeof PoostRoute
  '/privacy': typeof PrivacyRoute
  '/short-url': typeof ShortUrlRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/thanks': typeof ThanksRoute
  '/webhooks': typeof WebhooksRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/illurl-api': typeof AuthenticatedIllurlApiRoute
  '/message': typeof AuthenticatedMessageRoute
  '/article/$id': typeof ArticleIdRouteWithChildren
  '/f/$code': typeof FCodeRoute
  '/oauth2/$': typeof Oauth2SplatRoute
  '/topic/all': typeof TopicAllRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRouteWithChildren
  '/my/illurl': typeof AuthenticatedMyIllurlRoute
  '/rednote/manage': typeof AuthenticatedRednoteManageRoute
  '/webhooks/share': typeof AuthenticatedWebhooksShareRoute
  '/article/$id/edit': typeof ArticleIdEditRoute
  '/admin/webhooks/$id': typeof AuthenticatedAdminWebhooksIdRoute
  '/api/public/hooks/illurl-expiry-reminders': typeof ApiPublicHooksIllurlExpiryRemindersRoute
  '/api/public/hooks/notify-new-article': typeof ApiPublicHooksNotifyNewArticleRoute
  '/api/public/illurl/shorten': typeof ApiPublicIllurlShortenRoute
  '/api/public/oauth2/token': typeof ApiPublicOauth2TokenRoute
  '/api/public/push/latest': typeof ApiPublicPushLatestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/rednote/cn/$film/$open': typeof RednoteCnFilmOpenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$code': typeof CodeRoute
  '/donate': typeof DonateRoute
  '/feedback': typeof FeedbackRoute
  '/illurl-nocaptcha-15155': typeof IllurlNocaptcha15155Route
  '/mcp': typeof McpRoute
  '/new-announcement': typeof NewAnnouncementRoute
  '/new-article': typeof NewArticleRoute
  '/new-poost': typeof NewPoostRoute
  '/poost': typeof PoostRoute
  '/privacy': typeof PrivacyRoute
  '/short-url': typeof ShortUrlRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/thanks': typeof ThanksRoute
  '/webhooks': typeof WebhooksRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/illurl-api': typeof AuthenticatedIllurlApiRoute
  '/_authenticated/message': typeof AuthenticatedMessageRoute
  '/article/$id': typeof ArticleIdRouteWithChildren
  '/f/$code': typeof FCodeRoute
  '/oauth2/$': typeof Oauth2SplatRoute
  '/topic/all': typeof TopicAllRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/webhooks': typeof AuthenticatedAdminWebhooksRouteWithChildren
  '/_authenticated/my/illurl': typeof AuthenticatedMyIllurlRoute
  '/_authenticated/rednote/manage': typeof AuthenticatedRednoteManageRoute
  '/_authenticated/webhooks/share': typeof AuthenticatedWebhooksShareRoute
  '/article/$id/edit': typeof ArticleIdEditRoute
  '/_authenticated/admin/webhooks/$id': typeof AuthenticatedAdminWebhooksIdRoute
  '/api/public/hooks/illurl-expiry-reminders': typeof ApiPublicHooksIllurlExpiryRemindersRoute
  '/api/public/hooks/notify-new-article': typeof ApiPublicHooksNotifyNewArticleRoute
  '/api/public/illurl/shorten': typeof ApiPublicIllurlShortenRoute
  '/api/public/oauth2/token': typeof ApiPublicOauth2TokenRoute
  '/api/public/push/latest': typeof ApiPublicPushLatestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/rednote/cn/$film/$open': typeof RednoteCnFilmOpenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$code'
    | '/donate'
    | '/feedback'
    | '/illurl-nocaptcha-15155'
    | '/mcp'
    | '/new-announcement'
    | '/new-article'
    | '/new-poost'
    | '/poost'
    | '/privacy'
    | '/short-url'
    | '/sign-up'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/thanks'
    | '/webhooks'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/illurl-api'
    | '/message'
    | '/article/$id'
    | '/f/$code'
    | '/oauth2/$'
    | '/topic/all'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/webhooks'
    | '/my/illurl'
    | '/rednote/manage'
    | '/webhooks/share'
    | '/article/$id/edit'
    | '/admin/webhooks/$id'
    | '/api/public/hooks/illurl-expiry-reminders'
    | '/api/public/hooks/notify-new-article'
    | '/api/public/illurl/shorten'
    | '/api/public/oauth2/token'
    | '/api/public/push/latest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/rednote/cn/$film/$open'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$code'
    | '/donate'
    | '/feedback'
    | '/illurl-nocaptcha-15155'
    | '/mcp'
    | '/new-announcement'
    | '/new-article'
    | '/new-poost'
    | '/poost'
    | '/privacy'
    | '/short-url'
    | '/sign-up'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/thanks'
    | '/webhooks'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/illurl-api'
    | '/message'
    | '/article/$id'
    | '/f/$code'
    | '/oauth2/$'
    | '/topic/all'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/webhooks'
    | '/my/illurl'
    | '/rednote/manage'
    | '/webhooks/share'
    | '/article/$id/edit'
    | '/admin/webhooks/$id'
    | '/api/public/hooks/illurl-expiry-reminders'
    | '/api/public/hooks/notify-new-article'
    | '/api/public/illurl/shorten'
    | '/api/public/oauth2/token'
    | '/api/public/push/latest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/rednote/cn/$film/$open'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$code'
    | '/donate'
    | '/feedback'
    | '/illurl-nocaptcha-15155'
    | '/mcp'
    | '/new-announcement'
    | '/new-article'
    | '/new-poost'
    | '/poost'
    | '/privacy'
    | '/short-url'
    | '/sign-up'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/thanks'
    | '/webhooks'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/illurl-api'
    | '/_authenticated/message'
    | '/article/$id'
    | '/f/$code'
    | '/oauth2/$'
    | '/topic/all'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/webhooks'
    | '/_authenticated/my/illurl'
    | '/_authenticated/rednote/manage'
    | '/_authenticated/webhooks/share'
    | '/article/$id/edit'
    | '/_authenticated/admin/webhooks/$id'
    | '/api/public/hooks/illurl-expiry-reminders'
    | '/api/public/hooks/notify-new-article'
    | '/api/public/illurl/shorten'
    | '/api/public/oauth2/token'
    | '/api/public/push/latest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/rednote/cn/$film/$open'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CodeRoute: typeof CodeRoute
  DonateRoute: typeof DonateRoute
  FeedbackRoute: typeof FeedbackRoute
  IllurlNocaptcha15155Route: typeof IllurlNocaptcha15155Route
  McpRoute: typeof McpRoute
  NewAnnouncementRoute: typeof NewAnnouncementRoute
  NewArticleRoute: typeof NewArticleRoute
  NewPoostRoute: typeof NewPoostRoute
  PoostRoute: typeof PoostRoute
  PrivacyRoute: typeof PrivacyRoute
  ShortUrlRoute: typeof ShortUrlRoute
  SignUpRoute: typeof SignUpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ThanksRoute: typeof ThanksRoute
  WebhooksRoute: typeof WebhooksRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ArticleIdRoute: typeof ArticleIdRouteWithChildren
  FCodeRoute: typeof FCodeRoute
  Oauth2SplatRoute: typeof Oauth2SplatRoute
  TopicAllRoute: typeof TopicAllRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksIllurlExpiryRemindersRoute: typeof ApiPublicHooksIllurlExpiryRemindersRoute
  ApiPublicHooksNotifyNewArticleRoute: typeof ApiPublicHooksNotifyNewArticleRoute
  ApiPublicIllurlShortenRoute: typeof ApiPublicIllurlShortenRoute
  ApiPublicOauth2TokenRoute: typeof ApiPublicOauth2TokenRoute
  ApiPublicPushLatestRoute: typeof ApiPublicPushLatestRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  RednoteCnFilmOpenRoute: typeof RednoteCnFilmOpenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/short-url': {
      id: '/short-url'
      path: '/short-url'
      fullPath: '/short-url'
      preLoaderRoute: typeof ShortUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poost': {
      id: '/poost'
      path: '/poost'
      fullPath: '/poost'
      preLoaderRoute: typeof PoostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-poost': {
      id: '/new-poost'
      path: '/new-poost'
      fullPath: '/new-poost'
      preLoaderRoute: typeof NewPoostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-article': {
      id: '/new-article'
      path: '/new-article'
      fullPath: '/new-article'
      preLoaderRoute: typeof NewArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-announcement': {
      id: '/new-announcement'
      path: '/new-announcement'
      fullPath: '/new-announcement'
      preLoaderRoute: typeof NewAnnouncementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/illurl-nocaptcha-15155': {
      id: '/illurl-nocaptcha-15155'
      path: '/illurl-nocaptcha-15155'
      fullPath: '/illurl-nocaptcha-15155'
      preLoaderRoute: typeof IllurlNocaptcha15155RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$code': {
      id: '/$code'
      path: '/$code'
      fullPath: '/$code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/all': {
      id: '/topic/all'
      path: '/topic/all'
      fullPath: '/topic/all'
      preLoaderRoute: typeof TopicAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth2/$': {
      id: '/oauth2/$'
      path: '/oauth2/$'
      fullPath: '/oauth2/$'
      preLoaderRoute: typeof Oauth2SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$code': {
      id: '/f/$code'
      path: '/f/$code'
      fullPath: '/f/$code'
      preLoaderRoute: typeof FCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/message': {
      id: '/_authenticated/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof AuthenticatedMessageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/illurl-api': {
      id: '/_authenticated/illurl-api'
      path: '/illurl-api'
      fullPath: '/illurl-api'
      preLoaderRoute: typeof AuthenticatedIllurlApiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id/edit': {
      id: '/article/$id/edit'
      path: '/edit'
      fullPath: '/article/$id/edit'
      preLoaderRoute: typeof ArticleIdEditRouteImport
      parentRoute: typeof ArticleIdRoute
    }
    '/_authenticated/webhooks/share': {
      id: '/_authenticated/webhooks/share'
      path: '/webhooks/share'
      fullPath: '/webhooks/share'
      preLoaderRoute: typeof AuthenticatedWebhooksShareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rednote/manage': {
      id: '/_authenticated/rednote/manage'
      path: '/rednote/manage'
      fullPath: '/rednote/manage'
      preLoaderRoute: typeof AuthenticatedRednoteManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my/illurl': {
      id: '/_authenticated/my/illurl'
      path: '/my/illurl'
      fullPath: '/my/illurl'
      preLoaderRoute: typeof AuthenticatedMyIllurlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/webhooks': {
      id: '/_authenticated/admin/webhooks'
      path: '/admin/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rednote/cn/$film/$open': {
      id: '/rednote/cn/$film/$open'
      path: '/rednote/cn/$film/$open'
      fullPath: '/rednote/cn/$film/$open'
      preLoaderRoute: typeof RednoteCnFilmOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/latest': {
      id: '/api/public/push/latest'
      path: '/api/public/push/latest'
      fullPath: '/api/public/push/latest'
      preLoaderRoute: typeof ApiPublicPushLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth2/token': {
      id: '/api/public/oauth2/token'
      path: '/api/public/oauth2/token'
      fullPath: '/api/public/oauth2/token'
      preLoaderRoute: typeof ApiPublicOauth2TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/illurl/shorten': {
      id: '/api/public/illurl/shorten'
      path: '/api/public/illurl/shorten'
      fullPath: '/api/public/illurl/shorten'
      preLoaderRoute: typeof ApiPublicIllurlShortenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notify-new-article': {
      id: '/api/public/hooks/notify-new-article'
      path: '/api/public/hooks/notify-new-article'
      fullPath: '/api/public/hooks/notify-new-article'
      preLoaderRoute: typeof ApiPublicHooksNotifyNewArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/illurl-expiry-reminders': {
      id: '/api/public/hooks/illurl-expiry-reminders'
      path: '/api/public/hooks/illurl-expiry-reminders'
      fullPath: '/api/public/hooks/illurl-expiry-reminders'
      preLoaderRoute: typeof ApiPublicHooksIllurlExpiryRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/webhooks/$id': {
      id: '/_authenticated/admin/webhooks/$id'
      path: '/$id'
      fullPath: '/admin/webhooks/$id'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksIdRouteImport
      parentRoute: typeof AuthenticatedAdminWebhooksRoute
    }
  }
}

interface AuthenticatedAdminWebhooksRouteChildren {
  AuthenticatedAdminWebhooksIdRoute: typeof AuthenticatedAdminWebhooksIdRoute
}

const AuthenticatedAdminWebhooksRouteChildren: AuthenticatedAdminWebhooksRouteChildren =
  {
    AuthenticatedAdminWebhooksIdRoute: AuthenticatedAdminWebhooksIdRoute,
  }

const AuthenticatedAdminWebhooksRouteWithChildren =
  AuthenticatedAdminWebhooksRoute._addFileChildren(
    AuthenticatedAdminWebhooksRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIllurlApiRoute: typeof AuthenticatedIllurlApiRoute
  AuthenticatedMessageRoute: typeof AuthenticatedMessageRoute
  AuthenticatedAdminWebhooksRoute: typeof AuthenticatedAdminWebhooksRouteWithChildren
  AuthenticatedMyIllurlRoute: typeof AuthenticatedMyIllurlRoute
  AuthenticatedRednoteManageRoute: typeof AuthenticatedRednoteManageRoute
  AuthenticatedWebhooksShareRoute: typeof AuthenticatedWebhooksShareRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIllurlApiRoute: AuthenticatedIllurlApiRoute,
  AuthenticatedMessageRoute: AuthenticatedMessageRoute,
  AuthenticatedAdminWebhooksRoute: AuthenticatedAdminWebhooksRouteWithChildren,
  AuthenticatedMyIllurlRoute: AuthenticatedMyIllurlRoute,
  AuthenticatedRednoteManageRoute: AuthenticatedRednoteManageRoute,
  AuthenticatedWebhooksShareRoute: AuthenticatedWebhooksShareRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ArticleIdRouteChildren {
  ArticleIdEditRoute: typeof ArticleIdEditRoute
}

const ArticleIdRouteChildren: ArticleIdRouteChildren = {
  ArticleIdEditRoute: ArticleIdEditRoute,
}

const ArticleIdRouteWithChildren = ArticleIdRoute._addFileChildren(
  ArticleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CodeRoute: CodeRoute,
  DonateRoute: DonateRoute,
  FeedbackRoute: FeedbackRoute,
  IllurlNocaptcha15155Route: IllurlNocaptcha15155Route,
  McpRoute: McpRoute,
  NewAnnouncementRoute: NewAnnouncementRoute,
  NewArticleRoute: NewArticleRoute,
  NewPoostRoute: NewPoostRoute,
  PoostRoute: PoostRoute,
  PrivacyRoute: PrivacyRoute,
  ShortUrlRoute: ShortUrlRoute,
  SignUpRoute: SignUpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ThanksRoute: ThanksRoute,
  WebhooksRoute: WebhooksRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ArticleIdRoute: ArticleIdRouteWithChildren,
  FCodeRoute: FCodeRoute,
  Oauth2SplatRoute: Oauth2SplatRoute,
  TopicAllRoute: TopicAllRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksIllurlExpiryRemindersRoute:
    ApiPublicHooksIllurlExpiryRemindersRoute,
  ApiPublicHooksNotifyNewArticleRoute: ApiPublicHooksNotifyNewArticleRoute,
  ApiPublicIllurlShortenRoute: ApiPublicIllurlShortenRoute,
  ApiPublicOauth2TokenRoute: ApiPublicOauth2TokenRoute,
  ApiPublicPushLatestRoute: ApiPublicPushLatestRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  RednoteCnFilmOpenRoute: RednoteCnFilmOpenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
